print("Buen día, soy un programa de Alex1217z :D")
nombre = input("¿Como te llamas? ")
edad = int(input("¿Cuantos años tienes? ")  )
frase = input("¿Cual es tu frase favorita? ")
dinerillo = float(input("¿Cuanto dinero tienes ahorrado? "))
print("Hola!", nombre,  "es un placer")
print("Tu edad es", edad) 
print("Tu frase preferida es", frase)
print("Tienes ahorrado", dinerillo,"pesos ¡felicidades!")
print("Hasta luego ^^! wiwiwiw")
